# Generated by Django 5.1.15 on 2026-05-15 06:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "po_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique identifier for the purchase order (e.g., 'PO-2024-0001') - Auto generated if left blank",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("PARTIALLY_RECEIVED", "Partially Received"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Current status of the purchase order",
                        max_length=20,
                    ),
                ),
                ("supplier_name", models.CharField(max_length=255)),
                (
                    "supplier_reference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_contact",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "supplier_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_pos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wo_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique identifier for the work order (e.g., 'WO-2024-0001') - Auto generated if left blank",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("CANCELLED", "Cancelled"),
                            (
                                "PENDING_INSUFFICIENT_STOCK",
                                "Pending - Insufficient Stock",
                            ),
                            ("COMPLETED_FULLY_USED", "Completed - Fully Used"),
                            ("COMPLETED_PARTIALLY_USED", "Completed - Partially Used"),
                            ("COMPLETED_NOT_USED", "Completed - Not Used"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Current status of the work order",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        help_text="Priority level of the work order",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_work_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order",
                "verbose_name_plural": "Work Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_ordered",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "quantity_received",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "destination_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expected_po_items",
                        to="inventory.shelf",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.purchaseorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="po_items",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order Item",
                "verbose_name_plural": "Purchase Order Items",
                "ordering": ["order", "product__name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_ordered__gt", 0)),
                        name="po_item_quantity_ordered_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity_received__gte", 0)),
                        name="po_item_quantity_received_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_required",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "quantity_issued",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wo_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        help_text="The shelf from which stock will be pulled.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expected_wo_items",
                        to="inventory.shelf",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Order Item",
                "verbose_name_plural": "Work Order Items",
                "ordering": ["work_order", "product__name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_required__gt", 0)),
                        name="wo_item_quantity_required_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity_issued__gte", 0)),
                        name="wo_item_quantity_issued_non_negative",
                    ),
                ],
            },
        ),
    ]
